# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bb78781ce2e8e9dec3ee8f455a321fc7905c4e1185c14c1969679880a8f6336cb4d19667782e7cfb2542bdfb285dfaaf24b7e1a9f6a46d2d7243f4142d377a6

test:
  secret_key_base: 03b7b2263c871fdb7c24ce2e87d227b264d98af36a275a920655c91832d9cf77e5e450e260bd8e6744af500fd4b9b13f1d171b61738d0490e8107b4bb9bd5ef9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
